apiVersion: v1
kind: PersistentVolume
metadata:
  name: inventory-mongo-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  hostPath:
    path: /data/inventory-mongo
    type: DirectoryOrCreate