apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: {{ .Values.mongo.image | quote }}
          ports:
            - containerPort: 27017
          securityContext:
            runAsNonRoot: true
            runAsUser: 999
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: {{ .Values.mongo.resources.requests.cpu | quote }}
              memory: {{ .Values.mongo.resources.requests.memory | quote }}
            limits:
              cpu: {{ .Values.mongo.resources.limits.cpu | quote }}
              memory: {{ .Values.mongo.resources.limits.memory | quote }}
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.secretName }}
                  key: MONGO_ROOT_USER
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.secretName }}
                  key: MONGO_ROOT_PASSWORD
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: {{ .Values.mongo.storage.pvcName }}
