apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: {{ .Values.redis.image | quote }}
          args: ["--requirepass", "$(REDIS_PASSWORD)"]
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.secretName }}
                  key: REDIS_PASSWORD
          ports:
            - containerPort: 6379
          securityContext:
            runAsNonRoot: true
            runAsUser: 999
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: {{ .Values.redis.resources.requests.cpu | quote }}
              memory: {{ .Values.redis.resources.requests.memory | quote }}
            limits:
              cpu: {{ .Values.redis.resources.limits.cpu | quote }}
              memory: {{ .Values.redis.resources.limits.memory | quote }}
