apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.secretName }}
type: Opaque
data:
  # Base64 encoded values for the local environment
  MONGO_ROOT_USER: YWRtaW4=
  MONGO_ROOT_PASSWORD: YWRtaW5wYXNzd29yZA==
  MONGO_URI: bW9uZ29kYjovL2FkbWluOmFkbWlucGFzc3dvcmRAbW9uZ28tc2VydmljZToyNzAxNy9pbnZlbnRvcnlodWI/YXV0aFNvdXJjZT1hZG1pbg==
  JWT_SECRET: c3VwZXJfc2VjcmV0X2p3dF9rZXlfY2hhbmdlX21lX2luX3Byb2R1Y3Rpb24=
  REDIS_URL: cmVkaXM6Ly9yZWRpcy1zZXJ2aWNlOjYzNzk=
  KAFKA_BROKER: a2Fma2Etc2VydmljZTo5MDky
  REDIS_PASSWORD: cmVkaXNwYXNzd29yZDEyMw==
  REDIS_USE_TLS: ZmFsc2U=
  KAFKA_SASL_USERNAME: dXNlcjE=
  KAFKA_SASL_PASSWORD: a2Fma2FwYXNzd29yZDEyMw==
  KAFKA_USE_SSL: ZmFsc2U=
